import { useState } from 'react'
import AppLayout from '@/layouts/AppLayout'
import {
  Card,
  DateRefreshBar,
  ParamChip,
  SearchExportBar,
  StatusPill,
} from '@/components/ui'
import iconDownload from '@/assets/shared/icon-download.svg'
import iconView from '@/assets/shared/icon-view.svg'
import iconChevron from '@/assets/shared/icon-chevron-sm.svg'

const breachChips = [
  'BOD',
  'COD',
  'Flow',
  'NH4-N',
  'TSS',
  'pH',
  'NO3-N',
  'Totalizer',
  'TN',
  'Temp.',
  'Phosphorus',
]

const rows = Array.from({ length: 4 }, () => ({
  no: 1,
  stp: '14 MLD STP, Sarai, Haridwar',
  generatedOn: '19 May 2026, 05:30 PM',
  generatedBy: 'Kartik Verma',
}))

export default function ComplianceReport() {
  const [activeTab, setActiveTab] = useState<'plant' | 'monthly'>('plant')

  return (
    <AppLayout
      breadcrumbs={[
        { label: 'Contract & Compliance' },
        { label: 'Compliance Report', current: true },
      ]}
      toolbar={
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => setActiveTab('plant')}
              className={
                activeTab === 'plant'
                  ? 'h-9 rounded border border-[#0768d2] bg-[#0768d2] px-4 text-[12px] font-medium text-white'
                  : 'h-9 rounded border border-[#eff0f6] bg-white px-4 text-[12px] font-medium text-[#646464]'
              }
            >
              Plant Performance
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('monthly')}
              className={
                activeTab === 'monthly'
                  ? 'h-9 rounded border border-[#0768d2] bg-[#0768d2] px-4 text-[12px] font-medium text-white'
                  : 'h-9 rounded border border-[#eff0f6] bg-white px-4 text-[12px] font-medium text-[#646464]'
              }
            >
              Monthly Compliance
            </button>
          </div>
          <DateRefreshBar />
        </div>
      }
    >
      <Card className="overflow-hidden p-4">
        <SearchExportBar
          className="mb-4"
          extra={
            <div className="relative flex h-[33px] w-[185px] items-center rounded border border-[#eff0f6] bg-white px-3">
              <span className="text-[12px] font-medium text-[#646464]">
                All Months
              </span>
              <img
                src={iconChevron}
                alt=""
                className="absolute right-3 top-1/2 size-4 -translate-y-1/2"
              />
            </div>
          }
        />
        <div className="overflow-x-auto">
          <table className="w-full min-w-[1100px] border-collapse text-left">
            <thead>
              <tr className="bg-[#f7f8fa]">
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  S.No.
                </th>
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  STP
                </th>
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  Parameter Breach
                </th>
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  Generated On
                </th>
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  Generated By
                </th>
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  Status
                </th>
                <th className="px-4 py-3 text-[14px] font-medium text-[#646464]">
                  Details
                </th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, index) => (
                <tr key={index} className="border-b border-[#eff0f6]">
                  <td className="px-4 py-4 text-[14px] text-[#07121e]">{row.no}</td>
                  <td className="px-4 py-4 text-[14px] font-medium text-[#07121e]">
                    {row.stp}
                  </td>
                  <td className="px-4 py-4">
                    <div className="flex flex-wrap gap-1">
                      {breachChips.map((p) => (
                        <ParamChip key={p} label={p} active />
                      ))}
                    </div>
                  </td>
                  <td className="px-4 py-4 text-[14px] text-[#07121e]">
                    {row.generatedOn}
                  </td>
                  <td className="px-4 py-4 text-[14px] text-[#07121e]">
                    {row.generatedBy}
                  </td>
                  <td className="px-4 py-4">
                    <StatusPill label="Completed" tone="green" />
                  </td>
                  <td className="px-4 py-4">
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        className="flex size-8 items-center justify-center rounded border border-[#eff0f6] bg-white"
                        aria-label="Download report"
                      >
                        <img src={iconDownload} alt="" className="size-4" />
                      </button>
                      <button
                        type="button"
                        className="flex size-8 items-center justify-center rounded border border-[#eff0f6] bg-white"
                        aria-label="View report"
                      >
                        <img src={iconView} alt="" className="size-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </AppLayout>
  )
}
